# docker-compose.yml
services:
  db:
    image: postgres:15
    container_name: bot_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # <<< CORREÇÃO AQUI: Corrigido o nome da variável para POSTGRES_USER e POSTGRES_DB >>>
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - C:\Users\02.jonathan.lima\.ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    container_name: bot_python_app
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./IA:/app

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      ollama:
        condition: service_healthy
    env_file:
      - .env

    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
      OLLAMA_HOST: http://ollama:11434
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      REDIS_HOST: ${REDIS_HOST}               
      REDIS_PORT: ${REDIS_PORT}               
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      

volumes:
  postgres_data:
  redis_data:
  ollama:
